plugins:
  - jekyll-feed
  - jekyll-sitemap

# SEO Stuff
author: Femi Oluwatola
summary: A test site
lang: en
locale: en_GB
url: "https://<your domain name>"
baseurl: ""

# RSS feeds
feed:
  posts_limit: 20